<script lang="ts">let {data}=$props();</script>

<main class="min-h-screen bg-[#edf2f5]">
	<header class="site-header border-b-4 border-accent"><div class="mx-auto flex h-16 max-w-6xl items-center justify-between px-5 sm:px-8"><a href="/" class="wordmark"><span class="wordmark-mark">O</span>OWKR EXAM</a>{#if data.user}<div class="flex items-center gap-4 text-sm text-white"><span class="hidden text-white/80 sm:inline">{data.user.displayName} 님</span><form method="POST" action="/auth/logout"><button class="text-xs font-bold text-white/70 underline underline-offset-4 hover:text-white">로그아웃</button></form></div>{/if}</div></header>
	<div class="mx-auto max-w-6xl px-5 py-8 sm:px-8 sm:py-12"><div class="grid overflow-hidden rounded-sm border border-[#b8cbd6] bg-white shadow-sm lg:grid-cols-[1fr_320px]"><section class="p-8 sm:p-12"><p class="eyebrow">OWKR IN-HOUSE ADMINISTRATOR TEST</p><h1 class="mt-4 text-3xl font-bold leading-tight tracking-[-.04em] text-navy sm:text-5xl">OWKR 관리자<br/>선발시험</h1><p class="mt-7 max-w-xl leading-7 text-slate-600">내전 운영 역량을 확인하기 위한 공식 온라인 시험입니다. Discord 계정으로 로그인한 뒤 운영진에게 전달받은 응시 코드로 시험을 시작할 수 있습니다.</p><div class="mt-9 flex flex-wrap gap-3">{#if !data.user}<a class="btn" href="/auth/login">Discord로 로그인</a>{:else}<a class="btn" href="/exam">응시 코드 입력</a>{#if data.isAdmin}<a class="btn-secondary" href="/admin">관리자 시험 관리</a>{/if}{/if}</div></section><aside class="bg-[#e4f4fc] p-7 sm:p-8"><p class="border-b border-[#a9c9d9] pb-3 text-sm font-bold text-navy">응시 전 확인</p><ol class="mt-6 space-y-5 text-sm"><li class="flex gap-3"><b class="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-navy text-xs text-white">1</b><span><strong>Discord 로그인</strong><br/><span class="text-slate-600">본인 계정으로 로그인합니다.</span></span></li><li class="flex gap-3"><b class="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-navy text-xs text-white">2</b><span><strong>코드 입력</strong><br/><span class="text-slate-600">발급받은 6자리 코드를 입력합니다.</span></span></li><li class="flex gap-3"><b class="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-navy text-xs text-white">3</b><span><strong>60분 시험</strong><br/><span class="text-slate-600">답안은 자동 저장됩니다.</span></span></li></ol></aside></div>
		<div class="mt-6 grid gap-4 text-sm sm:grid-cols-3"><div class="rounded-sm border border-line bg-white p-5"><p class="font-bold text-navy">시험 시간</p><p class="mt-1 text-slate-600">시작 후 60분</p></div><div class="rounded-sm border border-line bg-white p-5"><p class="font-bold text-navy">응시 코드</p><p class="mt-1 text-slate-600">1인 1회, 계정 연동</p></div><div class="rounded-sm border border-line bg-white p-5"><p class="font-bold text-navy">채점 방식</p><p class="mt-1 text-slate-600">객관식 자동 · 서술형 검토</p></div></div>
	</div>
	<footer class="border-t border-[#c7d3da] bg-white"><div class="mx-auto flex max-w-6xl flex-col gap-2 px-5 py-6 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:px-8"><span>OWKR 관리자 선발시험 · 시험 운영 문의는 OWKR 운영진에게 해주세요.</span><a href="/privacy" class="font-semibold text-slate-600 underline underline-offset-4 hover:text-navy">개인정보처리방침</a></div></footer>
</main>
