<script lang="ts">
	import { onMount } from 'svelte';
	let {data}=$props(); let code=$state(''); let message=$state(''); let attempt=$state<any>(null); let index=$state(0); let values=$state<Record<string,string>>({}); let saving=$state(''); let remaining=$state(0); let confirm=$state(false); let q=$derived(attempt?.questions[index]);
	onMount(()=>{const timer=setInterval(()=>{if(attempt){remaining=Math.max(0,new Date(attempt.expiresAt).getTime()-Date.now());if(!remaining)submit(true)}},1000);const onShow=(e:PageTransitionEvent)=>{if(e.persisted)location.replace('/exam')};const onPop=()=>location.replace('/exam');addEventListener('pageshow',onShow);history.replaceState({examRoot:true},'', '/exam');addEventListener('popstate',onPop);return()=>{clearInterval(timer);removeEventListener('pageshow',onShow);removeEventListener('popstate',onPop)}});
	const fmt=(ms:number)=>`${Math.floor(ms/60000)}`.padStart(2,'0')+':'+`${Math.floor(ms/1000)%60}`.padStart(2,'0');
	async function start(){message='';const r=await fetch('/api/exam/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code})});const j=await r.json();if(!r.ok){message=j.message;return}attempt=j;values=Object.fromEntries(j.questions.map((x:any)=>[x.id,x.answer||'']));remaining=new Date(j.expiresAt).getTime()-Date.now()}
	let timers:Record<string,ReturnType<typeof setTimeout>>={};function save(id:string){clearTimeout(timers[id]);timers[id]=setTimeout(async()=>{saving='저장 중';const r=await fetch('/api/exam/answer',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({attemptQuestionId:id,value:values[id]})});saving=r.ok?'저장됨':'저장 실패'},500)}
	async function submit(timeout=false){if(!attempt)return;const r=await fetch('/api/exam/submit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({attemptId:attempt.id,timeout})});const j=await r.json();if(r.ok){attempt={...attempt,submittedAt:j.submittedAt};confirm=false}else message=j.message}
</script>

{#if !attempt}
	<main class="mx-auto min-h-screen max-w-xl px-5"><header class="flex h-20 items-center border-b border-ink"><a href="/" class="wordmark"><span class="wordmark-mark">O</span>OWKR EXAM</a></header><section class="py-20"><p class="eyebrow">EXAM ENTRY</p><h1 class="mt-4 text-3xl font-bold tracking-[-0.04em]">응시 코드 입력</h1><p class="mt-3 text-sm leading-6 text-stone-600">운영진에게 받은 6자리 코드를 입력하세요. 시험을 시작하면 제한시간 60분이 즉시 적용됩니다.</p><div class="mt-9 border-y border-ink py-6"><label class="label" for="code">응시 코드</label><input id="code" bind:value={code} maxlength="6" class="w-full text-center font-mono text-xl font-bold tracking-[0.42em] uppercase" placeholder="A7K3PX"/><button class="btn mt-4 w-full" onclick={start}>시험 시작</button>{#if message}<p class="mt-3 text-sm font-semibold text-red-700">{message}</p>{/if}</div></section></main>
{:else if attempt.submittedAt}
	<main class="mx-auto min-h-screen max-w-xl px-5"><header class="flex h-20 items-center border-b border-ink"><a href="/" class="wordmark"><span class="wordmark-mark">O</span>OWKR EXAM</a></header><section class="py-20"><p class="eyebrow">SUBMISSION COMPLETE</p><h1 class="mt-4 text-3xl font-bold tracking-[-0.04em]">답안이 제출되었습니다.</h1><p class="mt-4 text-sm leading-6 text-stone-600">제출 이후에는 답안을 변경할 수 없습니다. 주관식 답안의 채점 결과는 운영진이 확인합니다.</p><a href="/" class="btn mt-8">메인으로 돌아가기</a></section></main>
{:else}
	<main class="min-h-screen bg-white"><header class="border-b border-ink"><div class="mx-auto flex h-16 max-w-6xl items-center justify-between px-5"><span class="wordmark"><span class="wordmark-mark">O</span>OWKR EXAM</span><div class="text-right"><p class="text-[10px] font-bold tracking-widest text-stone-500">REMAINING TIME</p><p class="font-mono text-lg font-bold tabular-nums">{fmt(remaining)}</p></div></div></header><div class="mx-auto max-w-6xl px-5 py-7"><div class="mb-6 flex items-end justify-between border-b border-line pb-4"><div><p class="eyebrow">OWKR ADMINISTRATION EXAM</p><p class="mt-1 text-sm text-stone-600">문제 {index+1} / {attempt.questions.length}</p></div><span class="text-xs text-stone-500">{saving}</span></div><div class="grid gap-8 lg:grid-cols-[190px_minmax(0,1fr)]"><aside><p class="mb-3 text-xs font-bold tracking-wide text-stone-600">문항 목록</p><div class="grid grid-cols-5 gap-1.5">{#each attempt.questions as item,i}<button aria-label={`${i+1}번 문제`} onclick={()=>index=i} class="h-9 border text-xs font-bold {i===index?'border-ink bg-ink text-white':values[item.id]?.trim()?'border-blue-200 bg-sky text-navy':'border-line bg-white'}">{i+1}</button>{/each}</div><p class="mt-3 text-[11px] leading-5 text-stone-500">파란색: 답변 저장됨<br/>검정색: 현재 문제</p><button class="btn mt-7 w-full" onclick={()=>confirm=true}>시험 제출</button></aside>{#if q}<section><div class="border-t-2 border-ink pt-5"><div class="flex items-baseline justify-between"><p class="text-sm font-bold">문제 {index+1}</p><span class="text-sm text-stone-500">{q.points}점</span></div><h1 class="mt-6 whitespace-pre-wrap text-xl font-medium leading-9 tracking-[-.02em]">{q.content}</h1></div>{#if q.type==='multiple'}<div class="mt-9 border-y border-line">{#each q.options as option,i}<label class="flex cursor-pointer gap-4 border-b border-line px-3 py-4 last:border-0 hover:bg-stone-50"><input type="radio" name={q.id} value={String(i)} bind:group={values[q.id]} onchange={()=>save(q.id)} class="mt-0.5"/><span class="text-sm leading-6"><b class="mr-2">{i+1}.</b>{option}</span></label>{/each}</div>{:else}<textarea class="mt-8 min-h-52 w-full leading-7" bind:value={values[q.id]} oninput={()=>save(q.id)} placeholder={q.type==='short'?'답변을 입력하세요.':'답변을 충분히 작성하세요.'}></textarea>{/if}<div class="mt-10 flex justify-between border-t border-line pt-5"><button class="btn-secondary" disabled={index===0} onclick={()=>index--}>← 이전</button><button class="btn-secondary" disabled={index===attempt.questions.length-1} onclick={()=>index++}>다음 →</button></div></section>{/if}</div></div></main>
	{#if confirm}<div class="fixed inset-0 grid place-items-center bg-black/50 p-5"><section class="w-full max-w-md bg-white p-6 shadow-2xl"><p class="eyebrow">FINAL CONFIRMATION</p><h2 class="mt-3 text-xl font-bold">시험을 제출할까요?</h2><p class="mt-4 text-sm leading-6 text-stone-600">제출 후에는 답안을 수정하거나 다시 응시할 수 없습니다.<br/>미응답 문항: <b>{attempt.questions.filter((item:any)=>!values[item.id]?.trim()).length}개</b></p><div class="mt-7 flex justify-end gap-2"><button class="btn-secondary" onclick={()=>confirm=false}>계속 작성</button><button class="btn" onclick={()=>submit()}>제출하기</button></div></section></div>{/if}
{/if}
